name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]

    env:
      BINARY_NAME: kubectx-manager

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Create Output Directory
        run: mkdir -p dist

      - name: Build Binary
        run: |
          ext=""
          archive_cmd="tar -czf"
          file_ext="tar.gz"

          if [ "${{ matrix.goos }}" = "windows" ]; then
            ext=".exe"
            archive_cmd="zip -j"
            file_ext="zip"
          fi

          output_name="${BINARY_NAME}${ext}"
          archive_name="${BINARY_NAME}-${{ matrix.goos }}-${{ matrix.goarch }}.${file_ext}"

          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 \
            go build -o "$output_name" ./main.go

          mkdir -p archive
          $archive_cmd "dist/$archive_name" "$output_name"

          sha256sum "dist/$archive_name" >> dist/checksums.txt

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.tar.gz
            dist/*.zip
            dist/checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}